#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# (c) ACE 

import os

class Config(object):
    # get a token from @BotFather
    pass
    """
    BOT_TOKEN = os.environ.get("BOT_TOKEN", "7070340876:AAHtehdtPhZxFOImID-LOXs2NylTVDrcTNM")
    API_ID = int(os.environ["API_ID", 26606308]
    API_HASH = os.environ["API_HASH", "84d6c59a7ae2e1bc88dfe83c92121684"]
    AUTH_USERS = "6448912854"""
# jisko bhi is repo ko deploy karne me error aa raha ho ( https://t.me/ ) ye mere TG ka id ha message karke iska screen shot send kar dena me error solve kar dunga. 
